
services:
    rawphp_http.factory.client:
        class: RawPHP\Http\Factory\ClientFactory

    rawphp_http.factory.request:
        class: RawPHP\Http\Factory\RequestFactory

    rawphp_http.factory.response:
        class: RawPHP\Http\Factory\ResponseFactory
