
services:
    raw_http.factory.client:
        class: RawPHP\Http\Factory\ClientFactory

    raw_http.factory.request:
        class: RawPHP\Http\Factory\RequestFactory

    raw_http.factory.response:
        class: RawPHP\Http\Factory\ResponseFactory
